remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: James Besse
description: This website has an up-to-date record of the projects and publications I'm working on
footer: None
